// Code generated by 'yaegi extract blueassetgroup.com/reports-service/reportapi'. DO NOT EDIT.

package symbols

import (
	"blueassetgroup.com/reports-service/reportapi"
	"reflect"
)

func init() {
	Symbols["blueassetgroup.com/reports-service/reportapi/reportapi"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Init": reflect.ValueOf(reportapi.Init),

		// type definitions
		"Context":     reflect.ValueOf((*reportapi.Context)(nil)),
		"MongoHandle": reflect.ValueOf((*reportapi.MongoHandle)(nil)),
		"Option":      reflect.ValueOf((*reportapi.Option)(nil)),
		"Result":      reflect.ValueOf((*reportapi.Result)(nil)),
	}
}
